### ISSUE TITLE
cPickleCache will not build on Python 3.9 without trace refs

### ISSUE THREAD

**Issue by tschorr** [zopefoundation/persistent#124]
cPickleCache is relying on https://github.com/zopefoundation/persistent/blob/d4f1204d87bec113de5c2457eaa7878ec0f40ab3/persistent/cPickleCache.c#L664

which is no longer available on Python 3.9 without Py_TRACE_REFS being defined, s. https://github.com/python/cpython/pull/18332

As a result, cPickleCache can't be built + imported:

```
from persistent import cPickleCache
*** ImportError: /home/thomas/devel/plone/persistent/.tox/py39/lib/python3.9/site-packages/persistent/cPickleCache.cpython-39-x86_64-linux-gnu.so: undefined symbol: _Py_ForgetReference
```

Tests silently work around this.

It is still possible to import cPersistence though, so code in the package that does `import persistence` and then uses `persistent.Persistent`, e.g. https://github.com/zopefoundation/persistent/blob/d4f1204d87bec113de5c2457eaa7878ec0f40ab3/persistent/mapping.py#L33 will be fine. But client code that uses the items defined in __init__.py:

https://github.com/zopefoundation/persistent/blob/d4f1204d87bec113de5c2457eaa7878ec0f40ab3/persistent/__init__.py#L40

will only ever see the Python implementation of both Persistent and the pickle cache.

-> This is causing trouble in the Persistence package, ticket coming there.

**Comment by PythonLinks** [comment]
I wonder if we could use the ArrangoDB serialization protocol, VelocityPack, instead of Python Pickle.  
https://github.com/arangodb/velocypack

>covers all of JSON plus dates, integers, binary data and arbitrary precision numbers 
All this gives us the possibility to use the same byte sequence of data for transport, storage and (read-only) work. Using a single data format not only eliminates a lot of conversions but ?can also reduce runtime memory usage, as data does only need a single in-memory representation.

>The other popular formats we looked at have all some deficiency with respect to the above list. 

After reading more about it, it sounds more interesting than I initially thought.  
 What problems am I missing?  I am curious what other people think of this idea?

**Comment by icemac** [comment]
@tschorr Thank you for your analysis and @jamadden thank you for fixing this issue.
