### ISSUE TITLE
Install _compat.h

### ISSUE THREAD

**Issue by jamesjer** [zopefoundation/persistent#138]
The headers cPersistence.h and ring.h are listed in headers in setup.py, but _compat.h is not, so it is not installed like the others.  This is a problem because cPersistence.h has this on line 18:
```
#include "_compat.h"
```
The missing header causes the BTrees build to fail.

**Comment by jamadden** [comment]
As near as I can tell, this library has never installed the `_compat.h` header as such, even back when the first standalone release, 4.0.0, was made.
https://github.com/zopefoundation/persistent/blob/c9272cb57838ce0f4eab915cde4fa77aabb8a48d/setup.py#L64-L65

It is included as data installed alongside the .py files, though. Typically, that's the directory that winds up on the compiler command line. E.g., on my Raspbian box, I see BTrees compile with `-I/<path-to-venv>/local/lib/python2.7/site-packages`. BTrees includes `persistent/cPersistence.h`, which is next to `persistent/_compat.h` in that directory.

BTrees also ships with its own `_compat.h` header, and because of the use of unqualified paths in the `#include` lines, that's the one that should be used when compiling BTrees. I don't recall the vagaries of C include file order right now, but even if that one is picked up first before `persistent/_compat.h` when reading `persistent/cPersistence.h` I think that'd be ok: We get "lucky" in that the BTree version is a superset of the persistent version (as far as other .h files are concerned).

I had no trouble installing persistent 4.6.1 from source from PyPI and then installing BTrees 4.6.1 from source from PyPI (on 32-bit Raspbian arm just to be sure). 

Maybe it would help if you could provide more details about the failure you're seeing.

**Comment by jugmac00** [comment]
Maybe that's related to https://community.plone.org/t/valueerror-need-more-than-0-values-to-unpack-ploneintranet/5771/9 ?

**Comment by d-maurer** [comment]
Jürgen Gmach wrote at 2020-3-8 05:51 -0700:
>Maybe that's related to https://community.plone.org/t/valueerror-need-more-than-0-values-to-unpack-ploneintranet/5771/9 ?

It is unrelated: Here, apparently "_compat.h" is not found; there
"_compat.h" has been found but its "Python.h" include failed
(because the Python installation was binary only lacking development
resources like "Python.h").

**Comment by jugmac00** [comment]
Thanks Dieter. Maybe it's about time for me to learn at least some basic `C`.

**Comment by jamesjer** [comment]
Thanks for the helpful information.  It turns out that the way I had been injecting "-IBTrees" in to the build flags for the C compiler stopped working, leading to the compiler's inability to find _compat.h.  I fixed that issue and BTrees builds fine again.  Sorry for the noise.  Let's close this.
