### ISSUE TITLE
Troubles with PersistentMapping and copy.copy()

### ISSUE THREAD

**Issue by pakal** [zopefoundation/persistent#42]
I've always had troubles with  PersistentMapping.copy(), which caused connection._registered_objects to fill itself as if the PersistentMapping had been modified.

So so far, i used the "copy" module to do this job. But with 4.X releases, there has been a semantic change somewhere, and copy.copy() now creates a new mapping which however _changes_ when the original mapping has an item deleted. Below is the test which PASSES with ZODB 4.3.1. 
Is it a known behaviour ?

```
 def test_mapping_copy(self):

    a = PersistentMapping(dict(a=3, b=5))
    b = a.copy()
    c = copy.copy(a)
    d = copy.deepcopy(a)

    assert a == b
    assert a == c
    assert a == d
    assert a is not b
    assert a is not c
    assert b is not c
    assert a is not d

    del a["a"]
    assert b["a"]  # NOT impacted
    assert "a" not in c, c  # BUG, is impacted!
    assert d["a"]  # NOT impacted
```

**Comment by mgedmin** [comment]
Given a persistent mapping `pm`, `copy.copy(pm).data is pm.data`, which means that the two PersistentMapping instances always[*] share the same data.  Ouch. 

I would be curious to hear about any past versions of PersistentMapping where this wasn't the case.  Somehow I doubt that.

This can be fixed by implementing a custom `__copy__` method.  Would you care to provide a patch?  You could make `copy()` avoid marking the copy as changed while at it.  A simple implementation that returns `PersistentMapping(self)` ought to suffice, unless we care about people who may have overwritten PersistentMapping and rely on `.copy()` returning their subclass with maybe any extra attributes they may've added copied.

I'm not sure what the right thing to do is.

--

[*] "always" meaning "until they get stored in a ZODB, expunged from cache and loaded back, which would break the sharing"

**Comment by jamadden** [comment]
Is this a bug? `copy.copy` does the exact same thing with `UserDict` (on both Python 3 and Python 2). Since that's the superclass of PersistentMapping, I don't find the current behaviour surprising. If I wanted a deep copy, I would use `copy.deepcopy` or construct a new instance.

**Comment by jamadden** [comment]
> I would be curious to hear about any past versions of PersistentMapping where this wasn't the case. Somehow I doubt that.

It looks like this changed in ZODB 3.9. Prior to that ([ZODB 3.8](https://github.com/zopefoundation/ZODB/blob/3.8/src/persistent/mapping.py#L100)), PersistentMapping used a custom implementation of `__getstate__` that *copied* `self.data` into `self._container` for compatibility (and `copy.copy()` calls `__getstate__`, because `persistent.Persistent` has a `__reduce__` that does. Starting with ZODB 3.9, the current BWC approach was used.

So maybe this is a bug because it's a change in behavior. OTOH, 3.9 is 7 years old, so it's been this way for quite awhile.

**Comment by kilink** [comment]
This looks relevant: http://bugs.python.org/issue27141

**Comment by pakal** [comment]
OK so it looks like the porblem has to be solved at upper levels of UserList and UserDict instead.

**Comment by jamadden** [comment]
There seems to be agreement that this is an upstream problem (or possibly a downstream one), and there have been no comments in two years so it seems appropriate to close this issue.
