### ISSUE TITLE
Persistent.__setstate__ C SILENTLY fails on non-builtin dict

### ISSUE THREAD

**Issue by agroszer** [zopefoundation/persistent#60]
Key interning introduced in https://github.com/zopefoundation/persistent/commit/7bd85c189ae17be514f4989bfb8f79f4d8013943 makes ```__setstate__``` SILENTLY fail when a  non-builtin dict is passed as state.

See https://github.com/agroszer/persistent/commit/1c1cebaf79914420a9de61e55fb72a75981965b2 how to provoke that.

- is there any constraint that ```state``` must be a builtin dict ?
- the C and python implementation differs, because the python one does not fail
- a major issue is that it silently fails, just not setting attributes and returning

**Comment by stephan-hof** [comment]
I see a few possible options here:
* Check if this optimization is needed at all. The dict object got some improvements in newer python versions. For example: https://www.python.org/dev/peps/pep-0412/
However this applies only to python3 and not python2, so I think it's not a real option.
* Use of `PyMapping_Items` and `PyObject_SetItem` instead of `PyDict_Next`. If you need the speed of `PyDict_Next` a check via `PyDict_CheckExact` could be done. If it returns `False` use the generic methods as a fallback.
* raise an exception if the dict is not a builtin dict.
* Don't do the optimization if `PyDict_CheckExact` returns `False`. Which is the most promising one, since its easy to implement. Yes you loose the optimization if a non builtin dict comes in, but I guess this does not happen very often.
